services:
  db:
    image: postgres:latest
    container_name: postgresqlDB
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: db-volume
        target: "/var/lib/pgsql/data"
        read_only: false

volumes:
  db-volume:
    name: postgresqlDBvolume
